#cloud-config
package_upgrade: true
write_files:
  - path: /etc/systemd/system/docker.service.d/docker.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd
  - path: /etc/systemd/system/docker.service.d/options.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H unix:// -H tcp://0.0.0.0:2375
runcmd:
- curl -sSL https://get.docker.com/ | sh
- usermod -aG docker azureuser
- useradd -m deployuser
- usermod -aG docker deployuser
- mkdir /certs
- chown -R deployuser:docker /certs
- docker network create alf-net
- docker volume create kong_config_vol